services:
  postfix:
    image: postfix
    build:
      dockerfile: Dockerfile
      context: .
    container_name: postfix
    network_mode: host
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 256M
        reservations:
          memory: 128M
    restart: "no"
    environment: 
      - TZ=America/Sao_Paulo
